### ISSUE TITLE
Linear algebra module to-do list

### ISSUE THREAD

**Issue by mfkasim1** [xitorch/xitorch#3]
- [x] `svd` (taking the `n` lowest or uppermost decomposition, just like `symeig`)
- [ ] `solve`
  - [x] `(method="cg")`
  - [x] `(method="bicgstab")`
  - [ ] `(method="lgmres")`
- [ ] `symeig` (eigen decomposition for symmetric matrix)
  - [ ] `(method="lobpcg")`
  - [ ] stabilizing the backward calculation for degenerate case
